<?php

namespace App\Http\Controllers;

use Auth;
use App\Documents;

class DashboardController extends Controller
{
    public function index()
    {
        // return view('dashboard');

        $text = "<b>SPECIAL</b> ipsum dolor sit amet, consectetur adipiscing elit. In aliquam est felis, et vestibulum nibh luctus vitae. Nulla mi metus, eleifend quis libero eget, ornare vehicula risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec egestas sodales euismod. Mauris non aliquam turpis, eget pretium elit. Nulla sodales commodo ex, interdum pulvinar metus pretium et. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Aenean at urna id magna dignissim auctor. Duis quis interdum elit, a volutpat sem. Praesent eu placerat urna. Integer pharetra consectetur elit ac interdum. Nullam felis augue, maximus eu pellentesque eu, feugiat eu augue. Nullam nibh urna, rhoncus vitae euismod a, venenatis id ipsum. Nam volutpat tellus in blandit viverra. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In ultricies odio ac metus mollis, in semper metus facilisis. Nam sit amet tincidunt leo. Maecenas laoreet, tortor accumsan sodales fringilla, massa nisi dignissim velit, vitae ullamcorper ligula dolor eget nisl.

Duis eu ultricies urna. Nullam enim turpis, finibus faucibus viverra eget, laoreet sit amet ex. Morbi mi libero, egestas vitae pharetra vel, sagittis quis nibh. Suspendisse aliquet in diam nec imperdiet. Vivamus sed ligula eu purus tincidunt lobortis non vulputate risus. Morbi varius vel nulla fringilla gravida. Duis maximus lectus elit, in faucibus turpis feugiat sit amet. Cras in purus sit amet leo venenatis tempor. Sed tristique feugiat tellus, eget venenatis massa semper vel.

Sed pretium dolor id quam feugiat viverra sit amet at sapien. Fusce vitae pharetra risus. Sed molestie sodales ornare. Integer volutpat in mauris ac venenatis. Nulla viverra eleifend nunc, ac pulvinar felis pretium sed. Nulla sit amet pulvinar libero. Aliquam tempus ultrices metus, quis viverra magna fermentum et.

Donec cursus tristique ligula, volutpat mattis orci. Sed eget ipsum et libero efficitur viverra. Quisque massa purus, sollicitudin ac lacinia non, viverra at justo. Aenean magna enim, gravida ac tortor vitae, posuere ornare erat. Sed viverra dapibus pellentesque. Aenean orci libero, porta in nibh pulvinar, vestibulum auctor lectus. Proin vehicula dui id tortor porta, cursus rhoncus leo lobortis. Maecenas eu ante ac dolor vulputate tincidunt. Cras ut purus gravida, porta magna non, euismod velit. Quisque posuere tortor laoreet luctus semper. Suspendisse ut odio vel turpis porttitor faucibus vel vitae odio. Nam quis turpis ut purus pretium auctor.

Nunc tincidunt neque lectus, dictum cursus metus ultricies quis. Aliquam sed sapien feugiat, volutpat lectus sed, interdum nibh. Proin id aliquet quam. Aliquam erat volutpat. Quisque efficitur nisl elit, at consequat ante tempus vel. Sed ultrices at nisi ac feugiat. Donec vulputate sodales risus at fringilla. Nulla turpis ipsum, venenatis non enim non, blandit scelerisque ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aliquam purus metus, condimentum id pretium id, tristique sed purus. Phasellus semper sapien id sapien placerat, eu egestas nulla sollicitudin. Etiam in semper orci, id euismod dolor. Donec ut ante ultrices, varius ex non, dignissim dolor.

Aenean malesuada tortor in magna luctus, ut semper dui fringilla. Vestibulum faucibus, tortor at scelerisque tincidunt, erat metus vehicula nisl, non consequat sapien arcu quis nunc. Phasellus non tortor magna. Ut sem eros, malesuada sed lacinia in, egestas sed sem. Nunc elit dolor, aliquam luctus tincidunt quis, pretium id est. Cras eu aliquam tortor. Etiam ante nisl, interdum sit amet ex nec, dignissim bibendum eros. Quisque fringilla feugiat luctus. Integer dictum vitae lacus et sodales. Ut turpis velit, accumsan eu elit quis, aliquam lobortis felis. Praesent porttitor augue mauris, non vestibulum sapien finibus at. In ac dui ac eros commodo condimentum. Vivamus ac est a metus gravida lobortis at vel odio. Aenean vulputate dui gravida, fringilla ante quis, bibendum justo. Phasellus a enim vestibulum, ullamcorper justo in, molestie tellus. Donec a accumsan arcu.

In vitae risus est. Nullam eu pretium velit. Vivamus ante mi, volutpat ut urna id, dignissim posuere orci. Suspendisse in nisi ligula. Nulla facilisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin lobortis blandit pulvinar. In vitae accumsan sem, sit amet sollicitudin ante. Vestibulum at nisl ullamcorper, pharetra tellus ut, auctor dolor. Curabitur a felis commodo, consequat ligula in, auctor metus. Fusce ornare ullamcorper vulputate. Praesent metus velit, luctus sed purus non, aliquam molestie nisi. Mauris velit ante, tincidunt eget tortor sit amet, vulputate consequat dolor.

Donec eu turpis in nisl tincidunt convallis. Mauris at libero et tellus convallis interdum. In ut eros sed ipsum blandit tempus at sed nulla. Mauris ultrices volutpat nulla quis rutrum. Nunc fringilla euismod auctor. Vivamus laoreet sapien purus, aliquet dictum enim lobortis et. Aliquam consectetur diam non pellentesque auctor.

Fusce iaculis tincidunt lacus a luctus. Proin ac varius nunc. Duis pretium elementum tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur commodo, libero placerat cursus malesuada, nisl leo volutpat mauris, suscipit mattis ipsum velit quis mauris. Vestibulum tempus sit amet libero eget accumsan. Ut facilisis sem id odio lacinia pulvinar. Vivamus ac malesuada lectus, in sodales augue. Quisque maximus finibus dapibus. Suspendisse euismod mauris id arcu aliquam commodo. Duis viverra finibus euismod.

Fusce vitae accumsan tellus, a tempus elit. Pellentesque eu erat turpis. Morbi lacus mauris, tristique eu est quis, mollis lobortis ipsum. Nulla facilisi. Mauris a mi magna. Morbi eget risus et velit bibendum luctus nec eu metus. Suspendisse lorem lectus, ultrices eu tempor sodales, ultrices in diam. Fusce non bibendum ipsum, eu interdum tortor. Mauris non nibh egestas, fermentum metus at, pharetra lectus. Ut convallis diam in libero vulputate pulvinar. Fusce rhoncus libero ex, dictum tempus leo semper sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam quis sollicitudin tortor, vel auctor ex. Nunc mattis cursus lorem. Mauris nunc ligula, condimentum eu arcu et, lacinia fermentum urna. Sed finibus mauris id consequat imperdiet.

Quisque fermentum quam tortor, sed posuere augue porttitor id. Curabitur eget elementum libero. Morbi imperdiet turpis at turpis condimentum luctus. Nulla sagittis nunc convallis, luctus ante sit amet, varius magna. Integer vehicula venenatis ante sed laoreet. Fusce rhoncus diam quis mauris fringilla, a volutpat arcu pharetra. Nulla sagittis risus sed lectus semper, non tincidunt neque porttitor. Aliquam eu arcu lectus. Praesent mattis mollis risus, vitae placerat enim bibendum vel. Mauris ac diam maximus arcu finibus suscipit. Quisque lectus lorem, placerat ut mollis finibus, pharetra in enim. Aenean quis ligula pellentesque, ornare ante ac, maximus massa.

Proin in rutrum urna, at lobortis sem. Integer iaculis lorem quis pharetra dignissim. Nullam imperdiet est ut risus tempus, vel tincidunt tortor egestas. Sed a iaculis quam. Aliquam erat nisi, luctus eu mi non, tincidunt finibus enim. Proin tempus finibus metus imperdiet eleifend. Phasellus eu enim at nibh tempor laoreet. Pellentesque luctus, lectus eu varius feugiat, erat est malesuada erat, ac sagittis lorem elit interdum mi. Cras vitae malesuada dolor. Nullam sed magna a libero pretium gravida vel sed mauris. Cras at vulputate mi. Sed facilisis nisi egestas, fermentum neque non, viverra lacus. Mauris in dui volutpat, hendrerit ligula et, venenatis lacus. Fusce a ante laoreet, luctus ipsum sed, pulvinar arcu.

Nam ac tellus eget est porttitor pellentesque a sed felis. Curabitur velit mauris, bibendum volutpat massa non, hendrerit viverra massa. Quisque eget enim mollis, venenatis sapien eget, dapibus metus. Nullam auctor eros eget tortor lobortis, quis hendrerit nisi semper. Morbi ac neque tempor, ultrices nisl eleifend, molestie ex. Sed vehicula urna tortor, tristique vestibulum purus sagittis interdum. Proin eget sem neque. Quisque eu elementum risus. Proin sit amet massa porta, venenatis dui non, accumsan nunc. Suspendisse sit amet lectus urna. Integer gravida nunc sed velit placerat, sit amet gravida nisi sodales. Etiam vestibulum metus odio, in sodales lorem pulvinar non. Nunc maximus consectetur consectetur. Sed malesuada nisl justo, vitae finibus sem finibus nec. Donec eu luctus metus. Praesent convallis maximus felis id tempus.

Suspendisse eget risus vestibulum urna placerat placerat at in mi. Suspendisse blandit nulla ut elit posuere, nec rutrum turpis volutpat. Suspendisse tempor velit vel urna faucibus viverra. Vestibulum consequat ullamcorper blandit. Nam ultricies augue purus, at auctor ex interdum eu. Sed non sem at diam tristique vehicula. Morbi nec diam euismod, rutrum nunc sit amet, suscipit ipsum. Curabitur ut justo in libero aliquam gravida at quis neque. Cras sit amet aliquet lacus, at egestas nisl. Phasellus rhoncus est dolor, at pharetra libero bibendum ut. Curabitur molestie, tellus sit amet egestas aliquet, sem nulla faucibus justo, id elementum diam urna id urna. Donec massa metus, vehicula quis enim at, fermentum gravida orci.

Nullam eget pretium turpis, pretium congue libero. Sed convallis at dolor vitae congue. Etiam eu consectetur odio. Cras eget est magna. Mauris sit amet lacus nec nisl posuere consequat. Aliquam vulputate, felis id sollicitudin sagittis, sapien ante pharetra risus, lacinia lobortis eros eros et magna. Ut sed tortor sit amet justo varius efficitur sed eget leo. Quisque ligula turpis, condimentum ut auctor a, ullamcorper sed felis. Sed vulputate pulvinar iaculis. Ut sit amet felis eget sem iaculis malesuada. Suspendisse potenti. Vivamus ut cursus dolor.

Sed quis odio dictum, efficitur nisl at, ultrices odio. Quisque commodo tellus non condimentum blandit. Proin consequat auctor lacus, quis molestie magna finibus maximus. Nunc imperdiet ultricies diam sit amet vestibulum. Suspendisse tristique mi id efficitur luctus. Pellentesque ac sapien venenatis, faucibus eros in, facilisis purus. Sed egestas facilisis enim non tincidunt. Nullam tincidunt odio quis diam congue viverra. Maecenas ultrices consequat ultricies. Suspendisse ut dapibus nibh. Donec eget fermentum nibh. Nam vitae pulvinar odio. Maecenas at mollis risus. Integer lacinia, nisi at aliquet blandit, nisl nulla tincidunt metus, sit amet semper metus tellus nec turpis.

Fusce tempor ipsum in est sagittis efficitur. Donec commodo, metus nec vestibulum dapibus, leo lorem convallis augue, vitae pellentesque justo libero non ante. Nam fringilla urna quis turpis commodo dapibus. Cras lobortis rutrum augue. Sed magna leo, varius ut interdum sed, ultrices at dolor. Pellentesque eu congue mi. Fusce condimentum ultricies nunc, ac sollicitudin ligula pretium et. Sed varius nibh ac maximus venenatis.

Donec maximus nulla vel odio dictum vestibulum. Etiam vel eleifend est. Aliquam sodales vestibulum gravida. Nullam et turpis vitae enim molestie luctus. Quisque turpis diam, efficitur quis mollis vel, vestibulum ac mi. Duis sagittis dui lectus, et varius dui interdum facilisis. Praesent finibus, neque ut suscipit tempor, purus risus cursus quam, ut lacinia erat nunc quis neque. Vivamus eget mauris dolor. Donec laoreet diam eget massa semper, nec vestibulum tortor tincidunt. Curabitur eu vulputate turpis. Nunc mattis mauris ipsum. Etiam tortor est, consequat id neque a, lacinia dignissim magna. Vestibulum interdum justo nulla, nec fringilla nibh rhoncus nec. Ut risus orci, dapibus at consequat sit amet, sodales non sapien. Cras tortor justo, tempus nec blandit vitae, vestibulum nec lorem.

Proin sed neque non nisi pretium porttitor et sit amet ante. Pellentesque mattis condimentum augue. Nunc nibh mauris, dapibus ut interdum quis, fermentum et felis. Pellentesque eget tellus odio. Pellentesque at volutpat augue. Nullam ornare arcu vitae massa pretium molestie. Donec vestibulum eleifend neque, tincidunt feugiat odio ultrices et.

Maecenas ex purus, congue ultricies vulputate in, gravida quis enim. Nam porttitor lectus ac libero egestas tincidunt. Vestibulum vehicula porta dui non mollis. Vestibulum ipsum neque, mattis et ex ac, ultrices bibendum justo. Vivamus vulputate eu metus ac lacinia. Pellentesque commodo eros interdum magna cursus mollis. Donec tincidunt ex a eros tempus eleifend. Suspendisse potenti. Proin sagittis, nibh nec aliquam dictum, nibh lectus faucibus nunc, at mattis turpis augue nec dolor. Morbi cursus risus libero, vel fringilla est dapibus quis. Curabitur interdum dictum tempus. Cras vulputate dapibus dui ac lobortis. Cras ut bibendum est, eget condimentum odio. Curabitur convallis vel lectus quis finibus. Sed ac ligula in erat pellentesque aliquet. Donec accumsan tortor non aliquam scelerisque.

Phasellus eget orci id risus vestibulum dignissim. Mauris quis molestie lectus. Phasellus tortor purus, tincidunt in euismod sit amet, venenatis lacinia nulla. Aliquam ac elementum lorem, gravida pulvinar urna. Cras mollis ligula sem, ac consectetur justo mollis ut. Maecenas quis euismod leo. Etiam faucibus tincidunt ullamcorper. Etiam pellentesque massa sit amet arcu ullamcorper, non ornare enim aliquet. Aliquam euismod bibendum nisl ac imperdiet. Cras id libero metus. Aliquam nec nunc sed magna pellentesque bibendum vitae a dui. Sed vulputate, magna nec dictum venenatis, mi purus pretium tortor, eu accumsan tellus lacus vitae ante. Maecenas pellentesque, sapien consequat eleifend commodo, ante metus congue enim, in aliquet tortor elit commodo lorem. Curabitur congue nunc ut dolor imperdiet finibus. Mauris eget hendrerit eros, vitae condimentum libero. Morbi molestie mi sed nisl gravida vulputate.

In aliquet ut ligula id fringilla. In in pharetra enim. Morbi tempus efficitur neque quis commodo. Nam consectetur dolor in neque scelerisque, nec dignissim augue pharetra. Pellentesque mauris nisl, molestie vitae posuere at, ultrices in risus. Vestibulum at erat eget elit gravida maximus. Aenean semper augue sed dui blandit, vitae ultricies metus varius.

Mauris et odio eu sapien sodales tempor at ac magna. Cras convallis ultricies augue, vel faucibus magna. Maecenas at elit non urna rutrum porta. Sed vitae sapien eu massa tincidunt posuere. Sed facilisis eu augue a molestie. Morbi viverra risus turpis, non ultricies neque rutrum eleifend. Duis aliquam porttitor varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse arcu justo, porttitor sollicitudin massa at, hendrerit molestie justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse malesuada, sem quis ultricies egestas, turpis sem volutpat dolor, a aliquam arcu ligula ac nunc. Nam congue sodales arcu, id semper elit pretium id.

Suspendisse lacinia ante quam, eu rhoncus augue fermentum eget. Nam sed lectus dolor. Aenean elit sem, tristique non molestie sit amet, suscipit ornare massa. Vivamus mollis ante quis arcu bibendum, sit amet lacinia odio blandit. Vestibulum aliquam elit ac ex eleifend aliquet. Quisque sed risus sit amet neque suscipit volutpat ac id massa. Etiam et mi at arcu faucibus ultricies. Integer ut mi luctus, facilisis erat eget, pulvinar magna. Curabitur molestie volutpat nibh sed posuere. Nullam et convallis elit. Proin posuere sodales consectetur.

Curabitur eu faucibus mauris. Nam posuere venenatis felis, eget eleifend urna facilisis eu. Donec luctus faucibus sapien nec porta. Maecenas sit amet est nisi. Integer laoreet lorem libero, sit amet ultrices erat vestibulum ac. Fusce mollis justo ac mollis molestie. Nunc odio elit, faucibus non sapien vel, commodo maximus ligula. Etiam volutpat ex a est fringilla, quis porttitor lorem feugiat. Aliquam et diam eu risus tempor vestibulum. Vestibulum vel dolor ut nisi porta gravida in id ligula. Quisque rutrum lectus quis erat lacinia pretium. Aliquam urna nunc, porta a consequat quis, sodales et est. Duis eget turpis hendrerit, tempus dui eget, finibus nulla. Nunc lacinia diam a facilisis interdum. Etiam maximus, ex ac aliquet venenatis, ipsum velit iaculis arcu, sit amet malesuada odio risus eget nunc.

Donec tristique mauris mi, ut fermentum ante tempor at. Aenean imperdiet lorem non felis bibendum volutpat. Duis convallis lectus leo, id aliquet arcu feugiat non. Aliquam nec vehicula purus. Suspendisse commodo mi sed neque pharetra dignissim. Nullam tempus at justo eget hendrerit. Proin eleifend pharetra magna, eu mattis massa auctor ut. Nullam placerat, ligula ac egestas faucibus, risus lectus commodo nisi, in rutrum risus neque eget odio. Integer et ex eget lectus lacinia malesuada. Praesent accumsan leo id erat pellentesque, vel posuere nunc vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quam lectus, dignissim vitae nibh vitae, molestie pulvinar nunc. Sed laoreet odio quis urna tempus, in eleifend lorem fringilla. Sed metus est, bibendum nec eros quis, suscipit vehicula nulla.

Suspendisse efficitur lacus in ipsum maximus varius. Nulla pharetra, massa ut efficitur congue, purus turpis vestibulum sapien, at dictum magna lorem at lectus. Praesent tincidunt, nulla et pharetra aliquam, sem sem tempor tortor, non feugiat nisi nunc ac nisl. Nullam pretium tincidunt tellus, fermentum tristique tortor dictum sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse lacinia scelerisque tortor, ut posuere odio pellentesque ut. In vehicula turpis felis, in euismod erat euismod nec.

Nunc sed sem augue. Aliquam mattis faucibus libero, vitae venenatis nisi ullamcorper ac. Fusce eu est convallis, vulputate velit a, dapibus metus. Aliquam vitae congue massa. Fusce sem odio, faucibus eget velit nec, ultricies rhoncus urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus vitae nisl eu libero bibendum efficitur. Donec accumsan turpis id nisi tincidunt, vel pulvinar odio eleifend.

Suspendisse interdum, justo eu scelerisque elementum, enim tellus facilisis velit, eget elementum ligula dui in augue. Quisque a feugiat orci. Pellentesque in sem at nisl ultrices scelerisque. Morbi convallis nisl id nisi feugiat imperdiet. Vivamus nec massa at sapien porttitor mollis. Aliquam erat volutpat. Fusce cursus vehicula ante, eget vehicula est feugiat molestie. Aenean auctor velit sit amet urna pellentesque, non posuere metus pulvinar. Vivamus in turpis a quam vulputate ultricies in rutrum ipsum. Proin luctus enim nec euismod consectetur. Pellentesque condimentum nulla eu nisi aliquam sagittis. Vestibulum dictum velit sed nisl accumsan varius.

Vestibulum a faucibus odio. Nulla vitae suscipit nisi. Aliquam erat volutpat. In porta maximus tincidunt. Suspendisse pulvinar laoreet eros at sollicitudin. Fusce in finibus turpis, vitae imperdiet ipsum. Donec lobortis tellus non massa suscipit vestibulum. Quisque sit amet laoreet urna, rhoncus ornare tortor. Proin finibus urna dui, a euismod tortor suscipit ac. Praesent at venenatis lectus, porttitor lacinia magna. Proin ligula arcu, bibendum congue diam nec, molestie dapibus est. Phasellus rhoncus mauris vel mauris egestas, finibus condimentum nibh pretium. Maecenas eget lorem ac ligula sodales imperdiet. Cras vitae dui sem. Nam congue lorem sed pulvinar lobortis. Nulla lectus mi, interdum sit amet luctus eget, pulvinar sit amet massa.

Morbi elementum erat a fermentum rutrum. Duis dapibus, lectus non convallis iaculis, sapien purus interdum tortor, et sodales dui libero ut magna. Proin laoreet elit sit amet nisi faucibus, sed congue massa gravida. Aenean vel posuere nulla. Phasellus pellentesque est eu magna ultricies, sed volutpat mauris consectetur. Duis in nunc ligula. Duis scelerisque tempus facilisis. Mauris consequat congue auctor. Aliquam ipsum urna, tempus in enim nec, fringilla fringilla eros. Mauris non pharetra nisl. Morbi auctor lectus dapibus, venenatis dui id, tempus magna. Mauris eu velit a mauris ultricies porta et tristique purus. Ut eleifend, leo et tempus pulvinar, metus est semper ipsum, a elementum orci eros nec dui. Sed vestibulum ipsum id molestie gravida. Duis congue euismod semper. Aenean quis viverra ipsum, nec tempor libero.

Nunc tortor libero, mattis in lectus ut, vestibulum euismod felis. Nunc aliquam ligula et purus dignissim semper sed et nulla. Fusce libero sapien, commodo quis diam sed, maximus ultricies magna. Suspendisse viverra ullamcorper placerat. Sed faucibus bibendum mattis. Donec ornare urna a maximus consectetur. Vivamus pharetra ullamcorper leo eu varius. Donec tincidunt eget libero id sollicitudin. Ut porttitor sodales leo, id vehicula urna rhoncus quis. Aliquam sollicitudin ante a est interdum, a dignissim purus malesuada. Ut lacinia sit amet dolor nec gravida. Nunc malesuada ex ac lectus hendrerit, et volutpat dui commodo. Pellentesque ultrices elementum ligula, at suscipit arcu. Suspendisse at lorem quam. Morbi efficitur sodales nisi in auctor. Etiam at urna nunc.

Aliquam erat volutpat. Proin mattis ac lacus venenatis tincidunt. Pellentesque interdum auctor erat, vel bibendum dui consequat in. Curabitur posuere orci scelerisque pellentesque cursus. Aliquam erat volutpat. Proin vitae leo eleifend, consectetur enim in, porttitor dui. Cras eleifend nunc nec turpis varius sollicitudin. Aliquam volutpat velit nulla, quis rutrum enim bibendum id. Duis sed commodo elit. Nam sodales ullamcorper tempor.

Nullam et mollis libero, non tincidunt arcu. Praesent luctus vehicula ligula gravida ullamcorper. Duis elementum urna lorem, at efficitur purus ultrices quis. Morbi fringilla ipsum enim, at tristique risus fringilla in. Maecenas vitae facilisis enim. In hac habitasse platea dictumst. Proin gravida porttitor bibendum. Sed elementum ex sem, vel ultricies elit bibendum non. Ut et iaculis justo.

Nunc vitae arcu urna. Aliquam erat volutpat. In consequat vulputate tellus eget luctus. Donec eget massa vulputate, facilisis velit vitae, placerat mi. Ut non arcu mauris. Integer sed erat sollicitudin ligula auctor laoreet. Donec at augue posuere magna malesuada varius quis et libero. Etiam a felis quam. Phasellus orci quam, sodales non odio ut, luctus lacinia metus. Integer ullamcorper purus vel nulla rhoncus, nec feugiat arcu varius. Duis id nibh eget dui mattis varius. Vivamus hendrerit risus ligula, in posuere est tincidunt nec. Fusce non tortor commodo lacus lacinia ornare. Mauris id mauris eu enim dictum posuere et id purus. Pellentesque accumsan enim ac congue molestie. Mauris eget tortor sed mauris venenatis consectetur sed quis orci.

Mauris at tincidunt massa. Morbi suscipit quam vel est maximus, eu fermentum ligula pellentesque. Cras faucibus suscipit pulvinar. Nam semper ante orci, sed fermentum turpis ultrices sed. Suspendisse id massa vitae massa ultricies rhoncus eu venenatis risus. Praesent ultrices viverra erat at tincidunt. Donec fermentum ultrices massa ac lobortis. Nullam et enim ac quam vulputate molestie at sed risus. Vestibulum laoreet pellentesque nisi. In semper, dui quis viverra aliquet, nulla lorem dignissim libero, facilisis venenatis neque quam eget sem.

Vestibulum sed porttitor dolor. Phasellus dapibus diam et nunc tristique finibus. Pellentesque pellentesque vitae metus vitae posuere. In nisl ante, aliquam ac pharetra sed, fermentum et diam. In porttitor nec erat molestie commodo. Duis imperdiet maximus sem nec sollicitudin. Sed aliquet ex a scelerisque consectetur. Donec et nunc nisl. Mauris porta ante sit amet felis venenatis, vitae dictum ipsum sagittis. Cras commodo nisi eget enim faucibus laoreet. Proin condimentum consectetur pharetra.

Suspendisse sed dictum elit, quis faucibus quam. Phasellus sapien nulla, tempor et interdum in, sagittis ut nisl. Donec dapibus tempor sem a tincidunt. Morbi id justo ultrices, dapibus turpis in, imperdiet ipsum. Etiam viverra mi quis ex porta, egestas placerat justo posuere. Etiam convallis imperdiet nisi vitae pellentesque. Donec malesuada vel nunc et iaculis. Cras lobortis magna et tellus pellentesque bibendum. Morbi feugiat tempus eleifend. In quam orci, efficitur eu neque eget, convallis pellentesque sapien. Maecenas ut erat a risus sodales aliquet vitae egestas dui. Maecenas velit eros, luctus quis tortor ac, ultrices faucibus nisi. Etiam a tincidunt diam, nec blandit erat. Nam cursus, urna sed vulputate varius, nisl lectus consectetur turpis, vel consequat est tortor id sem.

Praesent gravida a nunc eget elementum. Suspendisse eu dolor sapien. Phasellus pulvinar tincidunt velit, vitae aliquam risus scelerisque et. Nullam lacus tellus, finibus in sollicitudin quis, varius vitae nunc. Praesent volutpat tincidunt nisl, sit amet commodo est maximus vel. Duis ut sapien nec magna feugiat pharetra ac at lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur id pharetra diam. Morbi pharetra risus eget consequat eleifend.

Nam commodo lorem enim, sed malesuada massa ornare sit amet. Sed vitae dictum orci, sit amet fermentum ex. Maecenas congue eget turpis ac egestas. Proin pretium sit amet risus sit amet congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin magna nunc, porttitor ut lacus sed, gravida placerat velit. Curabitur at velit augue. Vestibulum efficitur risus lorem, at vehicula lacus faucibus at. Curabitur tempus vehicula pulvinar. Etiam sagittis erat fermentum nulla sagittis interdum. Morbi semper dolor id turpis consectetur accumsan. Sed maximus, enim vel tincidunt vehicula, tellus velit egestas tellus, quis pharetra neque libero eget mi. Quisque sit amet accumsan elit. Donec rutrum tortor non eros dapibus sodales. Pellentesque ac tortor ipsum. Donec hendrerit, nunc a suscipit efficitur, neque nulla viverra augue, vel lobortis elit mi eu elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque aliquam lacus at tellus sed.";

        $arr = str_word_count(strip_tags($text), 2);
        $res = [];

        array_walk($arr, function(&$value, $key) use (&$res) {
            $res['words'][$key] = $value;
        });

        $doc = [
            'content' => $text,
            'owner' => Auth::user()->id
        ];

        Documents::create($doc);

    }
}
